version: 0.2.4.{build}
image:
  - Visual Studio 2017
cache:
- C:\ProgramData\chocolatey\bin -> scripts\ps\appveyor_install.ps1
- C:\ProgramData\chocolatey\lib -> scripts\ps\appveyor_install.ps1
- secure-file -> scripts\ps\appveyor_install.ps1
environment:
  OPENRCT2_ORG_TOKEN:
    secure: esyy5+5PRKZNYZ1hx1w/JpJGVwEC/YsJXnPp3cH98Yu7sW6/a03z/oJ1m9jhM/nDv5HL0swVK7pi9qQsN0utRg==
  BUILD_SERVER: AppVeyor
  PATH: C:\ProgramData\chocolatey\bin;$(PATH);C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
install:
- ps: >-
    .\scripts\ps\appveyor_install.ps1
platform:
  - x64
  - Win32
configuration: Release
before_build:
- ps: Set-Content -Path '.\resources\version.h' -Value "#define OPENRCT2_FILE_VERSION $($env:APPVEYOR_BUILD_VERSION -replace "\.", ",")"
- ps: Add-Content -Path '.\resources\version.h' -Value "#define OPENRCT2_PRODUCT_VERSION `"$($env:APPVEYOR_BUILD_VERSION)-$($env:APPVEYOR_REPO_COMMIT.Substring(0,10))`""
build:
  parallel: true
  project: openrct2.proj
test_script:
- ps: msbuild openrct2.proj /t:Test /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\artifacts\test-results.xml))
artifacts:
- path: .\artifacts\openrct2-portable*.zip
  name: OpenRCT2-portable
- path: .\artifacts\openrct2-installer*.exe
  name: OpenRCT2-installer
- path: .\artifacts\openrct2-symbols*.zip
  name: OpenRCT2 debug symbols
deploy_script:
- ps: >-
    .\scripts\ps\appveyor_deploy.ps1
