version: 0.0.8.{build}
image:
  - Visual Studio 2015
#  - Visual Studio 2017 RC
cache:
- C:\ProgramData\chocolatey\bin -> scripts\ps\appveyor_install.ps1
- C:\ProgramData\chocolatey\lib -> scripts\ps\appveyor_install.ps1
- secure-file -> scripts\ps\appveyor_install.ps1
environment:
  OPENRCT2_ORG_TOKEN:
    secure: leQX3xCQpmBLGuMqrxjFlzexDt96ypNRMM5TTRVHbGE8PwVg9crgeykLc2BIZU6HDHveJCHqh2cGMdHtHYJYcw==
  BUILD_SERVER: AppVeyor
  PATH: $(PATH);C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
install:
- ps: >-
    .\scripts\ps\appveyor_install.ps1
platform:
  - Win32
  - x64
configuration: Release
build:
  project: openrct2.proj
test_script:
- ps: msbuild openrct2.proj /t:TestNoRCT2 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\artifacts\test-results.xml))
artifacts:
- path: .\artifacts\openrct2-portable*.zip
  name: OpenRCT2-portable
- path: .\artifacts\openrct2-installer*.exe
  name: OpenRCT2-installer
- path: .\artifacts\openrct2-symbols*.zip
  name: OpenRCT2 debug symbols
deploy_script:
- ps: >-
    .\scripts\ps\appveyor_deploy.ps1
