name: 'Manage stale backtrace reports'
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 1
          only-issue-labels: 'backtrace.io'
          stale-issue-label: 'stale-backtrace'
          stale-issue-message: 'This issue is stale and will be closed tomorrow if no action is taken. To keep it open, leave a comment or remove the `stale-backtrace` label.'
          close-issue-message: 'This issue was closed due to inactivity.'
          operations-per-run: 200
